export const FIELD_OPTIONS = {
  appliance_fit: [
    { value: "Excellent", label: "Excellent" },
    { value: "Good", label: "Good" },
    { value: "Fair", label: "Fair" },
    { value: "Poor", label: "Poor" },
  ],
  design_feedback: [
    { value: "Excellent", label: "Excellent" },
    { value: "Good", label: "Good" },
    { value: "Fair", label: "Fair" },
    { value: "Poor", label: "Poor" },
  ],
  occlusion: [
    { value: "Excellent", label: "Excellent" },
    { value: "Good", label: "Good" },
    { value: "Fair", label: "Fair" },
    { value: "Poor", label: "Poor" },
  ],
  esthetics: [
    { value: "Excellent", label: "Excellent" },
    { value: "Good", label: "Good" },
    { value: "Fair", label: "Fair" },
    { value: "Poor", label: "Poor" },
  ],
  adjustments_made: [
    { value: "None", label: "None" },
    { value: "Minor", label: "Minor" },
    { value: "Moderate", label: "Moderate" },
    { value: "Major", label: "Major" },
  ],
  material: [
    { value: "Acrylic", label: "Acrylic" },
    { value: "Metal", label: "Metal" },
    { value: "Composite", label: "Composite" },
    { value: "Other", label: "Other" },
  ],
  shade: [
    { value: "A1", label: "A1" },
    { value: "A2", label: "A2" },
    { value: "A3", label: "A3" },
    { value: "A3.5", label: "A3.5" },
    { value: "A4", label: "A4" },
    { value: "B1", label: "B1" },
    { value: "B2", label: "B2" },
    { value: "B3", label: "B3" },
    { value: "B4", label: "B4" },
    { value: "C1", label: "C1" },
    { value: "C2", label: "C2" },
    { value: "C3", label: "C3" },
    { value: "C4", label: "C4" },
    { value: "D2", label: "D2" },
    { value: "D3", label: "D3" },
    { value: "D4", label: "D4" },
  ],
};